server:
  port: 8888
spring:
  application:
    name: feign-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
# feign默认已经集成了hystrix，需要手动开启 熔断处理
feign:
  hystrix:
    enabled: true
