server:
  port: 7380

spring:
  application:
    name: zuul-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: ribbon-consumer
    api-b:
      path: /api-b/**
      serviceId: feign-consumer
